k9s:
  cluster: k8s.stage.nb.no
  namespace:
    active: nbno
    lockFavorites: false
    favorites:
      - e2e
      - secret-agent
      - nbno
      - auau
      - default
  view:
    active: apps/v1/deployments nbno
  featureGates:
    nodeShell: false
  proxy: null
