k9s:
  cluster: docker-desktop
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - kube-public
      - default
      - auau
      - argocd
      - nbno-local
      - identity-platform
  view:
    active: v1/pods longhorn-system
  featureGates:
    nodeShell: false
  proxy: null
