k9s:
  cluster: rke2.stales.nb.no
  namespace:
    active: monitoring
    lockFavorites: false
    favorites:
      - monitoring
      - all
      - default
  view:
    active: ns
  featureGates:
    nodeShell: false
  proxy: null
